# Generated by Django 3.1.2 on 2020-10-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['index'], name='session_index_b66a3a_idx'),
        ),
    ]
