# Generated by Django 3.1.2 on 2020-12-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_matches_isrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
