# Generated by Django 3.1.2 on 2020-12-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201217_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('index', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('training_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
