# Generated by Django 3.1.2 on 2020-12-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='index',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='training',
            table='training',
        ),
    ]
