# Generated by Django 3.1.2 on 2021-01-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210111_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='training_id',
        ),
        migrations.AddField(
            model_name='training',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='training_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
